apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: 04-kub-base
    context: app
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml
